"""About page for the Immunopeptidomics QC Webapp."""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

import streamlit as st

st.title("About")
st.markdown(
    "This application supports quality control and exploratory analysis of immunopeptidomics "
    "datasets generated by mass spectrometry workflows such as "
    "[FragPipe](https://fragpipe.nesvilab.org/). It is designed for use by researchers "
    "evaluating sample quality prior to downstream biological interpretation."
)

st.markdown("---")

st.subheader("What This Application Does")
st.markdown(
    """
The Immunopeptidomics QC Webapp reads a peptide-level output table produced by FragPipe
(typically `combined_peptide.tsv`) and an optional MSstats intensity file, then generates
a structured quality control report across the following dimensions:

- **Identification overview:** MS/MS vs. match-between-runs (MBR) peptide counts per sample
- **Peptide length distribution:** comparison against expected length ranges for MHC class I
  and class II peptide populations
- **Spectral count and intensity distributions:** per-sample comparison of quantitative
  depth and reproducibility
- **Contaminant profiling:** detection of co-purified non-cellular proteins (e.g. keratins,
  trypsin, albumin) flagged by the `Cont_` prefix convention
- **Cross-sample peptide overlap:** Jaccard similarity and shared peptide count heatmaps
- **Protein source classification:** breakdown of SwissProt, TrEMBL, contaminant, and
  other database entries
- **Amino acid composition and sequence motifs:** positional frequency heatmap and sequence
  logo for 9-mer peptides; comparison against human proteome background
- **Charge state distribution:** overall and per-sample charge state profiles
- **PCA and sample clustering:** principal component analysis of log-transformed peptide
  intensities, with a Pearson correlation heatmap in hierarchical clustering order
- **Per-sample detail panels:** individual sample summaries, length distributions, motifs,
  and protein overlap
"""
)

st.subheader("Intended Use")
st.markdown(
    """
This tool is intended to support researchers conducting HLA immunopeptidomics experiments
who need to evaluate run quality, identify outlier samples, and compare technical or
biological replicates before committing to downstream analyses such as neoantigen
prioritisation, differential peptide presentation, or motif-based HLA typing.

It is designed for use in an academic or translational research context by users with
familiarity with mass spectrometry-based proteomics workflows. It is **not** a clinical
diagnostic product and must not be used as the basis for clinical decisions.
"""
)

st.subheader("Inputs Accepted")
st.markdown(
    """
| Input | Required | Description |
|-------|----------|-------------|
| FragPipe peptide table | Yes | `combined_peptide.tsv` or equivalent TSV/CSV with one row per unique peptide |
| MSstats intensity file | No | `msstats.csv` with `Intensity`, `Run`, and `Condition` columns; enables the intensity distribution section |

The peptide table must contain at minimum a peptide sequence column and at least one
sample-level Match Type column following the FragPipe naming convention
(`<sample> Match Type`, `<sample> Spectral Count`, `<sample> Intensity`).
"""
)

st.subheader("Interpreting the Output")
st.markdown(
    """
Each section of the report highlights one aspect of data quality. Key heuristics and
caveats are described inline in the report tabs and in the [Glossary](/Glossary) page.

Some figures (including PCA and overlap heatmaps) are computationally derived and depend
on the number and nature of samples present. Plots that cannot be meaningfully generated
for a given dataset are suppressed with an explanatory note.

All figures are interactive (pan, zoom, hover). The HTML report download produces a
self-contained file suitable for sharing with collaborators.
"""
)

st.subheader("User Accounts and Run History")
st.markdown(
    """
Registered users can save completed analyses to their account and revisit them in future
sessions via the **My Runs** page. Saved runs can also be compared side-by-side to assess
batch-to-batch or replicate-to-replicate consistency.

Run data is stored locally on the server in a per-user directory. Account passwords are
stored as bcrypt hashes; no plain-text credentials are retained.
"""
)

st.subheader("Technical Notes")
st.markdown(
    """
- Built with [Streamlit](https://streamlit.io/) and [Plotly](https://plotly.com/)
- PCA uses scikit-learn's `PCA` on log-transformed, min-value-imputed intensity matrices
- Sequence logos are rendered via [logomaker](https://logomaker.readthedocs.io/)
- Hierarchical clustering for the correlation heatmap uses Ward linkage with Euclidean distance
- Contaminant detection is based on the `Cont_` prefix convention in FragPipe FASTA databases
"""
)
